const $=s=>document.querySelector(s);
const fmt=(n,d=1)=>Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:d,minimumFractionDigits:d});
const int=n=>Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:0});
const pct=(n,d=1)=>`${fmt((Number(n||0))*100,d)}%`;
const PAGES=[['inicio','🏠 Inicio'],['indicadores','📊 Indicadores'],['pago','💳 Código Pago'],['nc','⚠ NC'],['plantilla','👥 Plantilla'],['items','📦 Items'],['tendencias','📈 Tendencias'],['reportes','📄 Reportes'],['config','⚙ Configuración']];
const C={region:0,dm:1,tienda:2,mes:3,semana:4};
let M, state={page:'inicio',region:'',dm:'',tienda:'',mes:'',weeks:[],trendMetric:'IPLH'};
const metricOffset=5;
const mi=k=>metricOffset+M.metrics.indexOf(k);
const dim=(r,k)=>M.dims[k][r[C[k]]]||'';
const val=(r,k)=>+r[mi(k)]||0;
const rowsBase=()=>M.rows;
const avg=(rs,k)=>{const a=rs.map(r=>val(r,k)).filter(v=>Number.isFinite(v)); return a.length?a.reduce((x,y)=>x+y,0)/a.length:0};
const sum=(rs,k)=>rs.reduce((t,r)=>t+val(r,k),0);
const round=(n,d=1)=>Number(n||0).toFixed(d);
const metricLabel=k=>M.metricLabels[k]||k;
const monthRank=m=>M.monthOrder.indexOf(m)>=0?M.monthOrder.indexOf(m):99;
function filtered(includeWeeks=true){return M.rows.filter(r=>(!state.region||dim(r,'region')===state.region)&&(!state.dm||dim(r,'dm')===state.dm)&&(!state.tienda||dim(r,'tienda')===state.tienda)&&(!state.mes||dim(r,'mes')===state.mes)&&(!includeWeeks||!state.weeks.length||state.weeks.includes(String(r[C.semana]))));}
function currentAndPrev(){const all=filtered(false); let weeks=state.weeks.length?state.weeks.map(Number).sort((a,b)=>a-b):[...new Set(all.map(r=>r[C.semana]))].sort((a,b)=>a-b).slice(-1); const current=all.filter(r=>weeks.includes(r[C.semana])); const prevWeeks=weeks.map(w=>w-1); const prev=all.filter(r=>prevWeeks.includes(r[C.semana])); return {current,prev,weeks,prevWeeks,all};}
function delta(now,old){return old?((now-old)/Math.abs(old))*100:0}
function statusBy(metric,v){
 if(metric==='Exactitud_Kronos') return v>=.95&&v<=1.05?['Excelente','good']:v>=.9&&v<=1.10?['Atención','warn']:['Riesgo','bad'];
 if(metric==='NC_Pct') return v<=.05?['Excelente','good']:v<=.10?['Atención','warn']:['Riesgo','bad'];
 if(metric==='Ratio') return v<=1.6?['Excelente','good']:v<=2?['Atención','warn']:['Riesgo','bad'];
 if(metric==='Plantilla_Cobertura') return v>=.95?['Excelente','good']:v>=.90?['Atención','warn']:['Riesgo','bad'];
 if(metric==='IPLH') return v>=14?['Excelente','good']:v>=12?['Atención','warn']:['Riesgo','bad'];
 if(metric==='TPLH') return v>=6?['Excelente','good']:v>=5?['Atención','warn']:['Riesgo','bad'];
 return v>=0?['Excelente','good']:['Riesgo','bad'];
}
function score(rows){
 const cov=avg(rows,'Plantilla_Ideal')?avg(rows,'Plantilla_Real')/avg(rows,'Plantilla_Ideal'):0;
 const s={
  IPLH:Math.min(100,avg(rows,'IPLH')/14*100),
  TPLH:Math.min(100,avg(rows,'TPLH')/6*100),
  Ratio:Math.max(0,100-(Math.max(0,avg(rows,'Ratio')-1.5)*45)),
  Exactitud:Math.max(0,100-(Math.abs(avg(rows,'Exactitud_Kronos')-1)*800)),
  NC:Math.max(0,100-(avg(rows,'NC_Pct')*700)),
  Plantilla:Math.min(100,cov*100),
  Items:Math.min(100,avg(rows,'Items_ADT')/2.3*100)
 };
 const weights={IPLH:.17,TPLH:.12,Ratio:.12,Exactitud:.20,NC:.17,Plantilla:.12,Items:.10};
 const total=Object.keys(s).reduce((t,k)=>t+s[k]*weights[k],0);
 const status=total>=88?'Excelente':total>=75?'Atención':'Riesgo';
 const cls=total>=88?'good':total>=75?'warn':'bad';
 const sorted=Object.entries(s).sort((a,b)=>b[1]-a[1]);
 return {total:Math.round(total),status,cls,fortalezas:sorted.slice(0,3),oportunidades:sorted.slice(-3).reverse(),components:s};
}
function renderNav(){ $('#nav').innerHTML=PAGES.map(p=>`<button class="navbtn ${state.page===p[0]?'active':''}" data-page="${p[0]}">${p[1]}</button>`).join(''); document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render();document.querySelector('.sidebar').classList.remove('open')}); }
function related(k){
 const rs=M.rows.filter(r=>(k==='region'||!state.region||dim(r,'region')===state.region)&&(k==='dm'||!state.dm||dim(r,'dm')===state.dm)&&(k==='tienda'||!state.tienda||dim(r,'tienda')===state.tienda)&&(k==='mes'||!state.mes||dim(r,'mes')===state.mes));
 let vals=[...new Set(rs.map(r=>k==='semana'?String(r[C.semana]):dim(r,k)).filter(Boolean))];
 if(k==='mes') vals.sort((a,b)=>monthRank(a)-monthRank(b)); else if(k==='semana') vals.sort((a,b)=>+a-+b); else vals.sort((a,b)=>a.localeCompare(b,'es'));
 return vals;
}
function renderFilters(){
 const fields=[['region','Región'],['dm','DM'],['tienda','Tienda'],['mes','Mes']];
 $('#filters').innerHTML=fields.map(([k,l])=>`<div class="field"><label>${l}</label><select data-filter="${k}"><option value="">Todos</option>${related(k).map(v=>`<option value="${esc(v)}" ${state[k]===v?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')+`<div class="field weeks"><label>Semanas</label><div class="weekbox">${related('semana').map(w=>`<button class="week ${state.weeks.includes(String(w))?'on':''}" data-week="${w}">${w}</button>`).join('')}</div></div>`;
 document.querySelectorAll('[data-filter]').forEach(el=>el.onchange=e=>{const k=e.target.dataset.filter; state[k]=e.target.value; if(k==='region'){state.dm='';state.tienda=''} if(k==='dm')state.tienda=''; if(k==='mes')state.weeks=[]; render();});
 document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{const w=String(b.dataset.week); state.weeks=state.weeks.includes(w)?state.weeks.filter(x=>x!==w):[...state.weeks,w].sort((a,b)=>+a-+b); render();});
}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function kpi(title,value,metric,old){const d=delta(value,old); const [st,cls]=statusBy(metric,value); const show=metric==='NC_Pct'||metric==='Exactitud_Kronos'?pct(value,1):fmt(value, metric==='Ratio'||metric==='TPLH'||metric==='Items_ADT'?2:1); return `<div class="kpi ${cls}"><div class="kpi-top"><span>${title}</span><b>${st}</b></div><div class="kpi-num">${show}</div><div class="spark">${spark(currentAndPrev().all,metric)}</div><div class="var ${d>=0?'up':'down'}">${d>=0?'↑':'↓'} ${Math.abs(d).toFixed(1)}% vs semana previa</div></div>`}
function spark(rows,k){const ws=[...new Set(rows.map(r=>r[C.semana]))].sort((a,b)=>a-b).slice(-10); const vals=ws.map(w=>avg(rows.filter(r=>r[C.semana]===w),k)); const min=Math.min(...vals), max=Math.max(...vals); const W=140,H=32,p=3; const sx=i=>p+i*(W-2*p)/Math.max(vals.length-1,1); const sy=v=>H-p-((v-min)/(max-min||1))*(H-2*p); return `<svg viewBox="0 0 ${W} ${H}">${vals.map((v,i)=>i?`<line x1="${sx(i-1)}" y1="${sy(vals[i-1])}" x2="${sx(i)}" y2="${sy(v)}"/>`:``).join('')}</svg>`}
function groupBy(rows,by,k,mode='avg'){const o={}; rows.forEach(r=>{const name=by==='semana'?String(r[C.semana]):dim(r,by); (o[name]??=[]).push(r)}); return Object.entries(o).map(([name,rs])=>({name,value:mode==='sum'?sum(rs,k):avg(rs,k),rows:rs})).sort((a,b)=>b.value-a.value);}
function entryList(rows,type){const rowSet=new Set(rows.map(r=>r._i)); const raw=type==='pago'?M.payments:M.nc; const names=type==='pago'?M.paymentTypes:M.ncTypes; return raw.filter(e=>rowSet.has(e[0])&&e[2]>0).map(e=>({row:M.rows[e[0]],name:names[e[1]],value:+e[2]}));}
function entryGroup(rows,type){const o={}; entryList(rows,type).forEach(e=>o[e.name]=(o[e.name]||0)+e.value); const total=Object.values(o).reduce((a,b)=>a+b,0)||1; return Object.entries(o).map(([name,value])=>({name,value,pct:value/total})).sort((a,b)=>b.value-a.value);}
function smartRows(current,prev,type){const now=entryGroup(current,type); const old=entryGroup(prev,type); const oldMap=Object.fromEntries(old.map(x=>[x.name,x.value])); return now.map(x=>{const p=oldMap[x.name]||0, d=delta(x.value,p), cls=x.pct>.30||d>20?'bad':x.pct>.15||d>8?'warn':'good'; return {...x,previous:p,delta:d,cls,state:(cls==='good'?'Excelente':cls==='warn'?'Atención':'Riesgo')};});}
function smartTable(items,label='Concepto'){return `<table class="smart"><thead><tr><th>${label}</th><th>Valor</th><th>%</th><th>Semana ant.</th><th>Variación</th><th>Semáforo</th><th>Estado</th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${fmt(x.value,1)}</td><td>${pct(x.pct,1)}</td><td>${fmt(x.previous,1)}</td><td class="${x.delta>=0?'badtxt':'goodtxt'}">${x.delta>=0?'+':''}${fmt(x.delta,1)}%</td><td><span class="dot ${x.cls}"></span></td><td><span class="pill ${x.cls}">${x.state}</span></td></tr>`).join('')}</tbody></table>`}
function alerts(cur,prev){
 const items=[];
 const nc=smartRows(cur,prev,'nc')[0]; if(nc) items.push({type:'NC',title:`NC ${nc.name}`,desc:'Incidencia con mayor impacto',impact:nc.value*(1+Math.max(nc.delta,0)/100),delta:nc.delta,cls:nc.cls});
 const pago=smartRows(cur,prev,'pago')[0]; if(pago) items.push({type:'Código Pago',title:`Código: ${pago.name}`,desc:'Horas administrativas con mayor peso',impact:pago.value*(1+Math.max(pago.delta,0)/100),delta:pago.delta,cls:pago.cls});
 const itemsReal=avg(cur,'Items_Reales'), itemsK=avg(cur,'Items_Kronos'), prevItems=avg(prev,'Items_Reales'); const devItems=itemsK?((itemsReal-itemsK)/itemsK)*100:0; items.push({type:'Items',title:'Items Reales vs Kronos',desc:`Desviación ${fmt(devItems,1)}%`,impact:Math.abs(devItems),delta:delta(itemsReal,prevItems),cls:Math.abs(devItems)>8?'bad':Math.abs(devItems)>4?'warn':'good'});
 const ex=avg(cur,'Exactitud_Kronos'), exPrev=avg(prev,'Exactitud_Kronos'); items.push({type:'Forecast',title:'Exactitud Kronos',desc:`Rango objetivo 95% a 105%`,impact:Math.abs(ex-1)*100,delta:(ex-exPrev)*100,cls:ex>=.95&&ex<=1.05?'good':ex>=.9&&ex<=1.10?'warn':'bad'});
 const cov=avg(cur,'Plantilla_Ideal')?avg(cur,'Plantilla_Real')/avg(cur,'Plantilla_Ideal'):0; const covPrev=avg(prev,'Plantilla_Ideal')?avg(prev,'Plantilla_Real')/avg(prev,'Plantilla_Ideal'):0; items.push({type:'Plantilla',title:'Cobertura plantilla',desc:`Cobertura ${pct(cov,1)}`,impact:Math.abs(1-cov)*100,delta:(cov-covPrev)*100,cls:cov>=.95?'good':cov>=.90?'warn':'bad'});
 return items.sort((a,b)=>b.impact-a.impact).slice(0,4);
}
function alertBox(a){return `<div class="alert ${a.cls}"><div class="alert-icon">${a.cls==='good'?'✓':a.cls==='warn'?'!':'!'}</div><div><b>${a.title}</b><p>${a.desc}</p><small>${a.type}</small></div><strong>${a.delta>=0?'+':''}${fmt(a.delta,1)}${a.type==='Forecast'||a.type==='Plantilla'?' pp':'%'}</strong></div>`}
function lineChart(rows,k){const ws=[...new Set(rows.map(r=>r[C.semana]))].sort((a,b)=>a-b); const vals=ws.map(w=>avg(rows.filter(r=>r[C.semana]===w),k)); return svgLine(ws,vals,metricLabel(k),k==='NC_Pct'||k==='Exactitud_Kronos');}
function svgLine(labels,vals,title,isPct=false){const W=780,H=300,p=54; const max=Math.max(...vals,1), min=Math.min(...vals,0); const pad=(max-min)*.15||1; const lo=min-pad, hi=max+pad; const sx=i=>p+i*(W-2*p)/Math.max(labels.length-1,1); const sy=v=>H-p-((v-lo)/(hi-lo))*(H-2*p); const yTicks=[0,.25,.5,.75,1].map(t=>lo+t*(hi-lo)); return `<svg viewBox="0 0 ${W} ${H}" class="chart"><rect width="100%" height="100%" rx="20" fill="#fffaf0"/><line x1="${p}" x2="${p}" y1="${p-10}" y2="${H-p}" stroke="#78958a"/><line x1="${p}" x2="${W-p}" y1="${H-p}" y2="${H-p}" stroke="#78958a"/>${yTicks.map(v=>`<line x1="${p}" x2="${W-p}" y1="${sy(v)}" y2="${sy(v)}" stroke="#dfe7e2"/><text x="${p-10}" y="${sy(v)+4}" text-anchor="end" font-size="12" fill="#66736d">${isPct?pct(v,0):fmt(v,1)}</text>`).join('')}<path d="${vals.map((v,i)=>(i?'L':'M')+sx(i)+' '+sy(v)).join(' ')}" fill="none" stroke="#006241" stroke-width="4" stroke-linecap="round"/>${vals.map((v,i)=>`<circle cx="${sx(i)}" cy="${sy(v)}" r="5" fill="#00a862"><title>Semana ${labels[i]}: ${isPct?pct(v,1):fmt(v,2)}</title></circle><text x="${sx(i)}" y="${sy(v)-10}" text-anchor="middle" font-size="11" fill="#003c2f" font-weight="800">${isPct?pct(v,0):fmt(v,1)}</text>`).join('')}${labels.map((l,i)=>`<text x="${sx(i)}" y="${H-20}" text-anchor="middle" font-size="12" fill="#66736d">${l}</text>`).join('')}<text x="${p}" y="28" fill="#006241" font-size="16" font-weight="900">${title}</text><text x="${W/2}" y="${H-5}" text-anchor="middle" font-size="12" fill="#66736d">Semana</text></svg>`}
function barChart(items,title,maxBars=8){const top=items.slice(0,maxBars), W=720,H=Math.max(260,top.length*36+90),p=58; const max=Math.max(...top.map(x=>x.value),1); const y=i=>p+i*((H-p*1.25)/top.length); return `<svg viewBox="0 0 ${W} ${H}" class="chart"><rect width="100%" height="100%" rx="20" fill="#fffaf0"/><line x1="${p+110}" x2="${W-p}" y1="${H-45}" y2="${H-45}" stroke="#78958a"/>${[0,.25,.5,.75,1].map(t=>`<line x1="${p+110+t*(W-p*2-110)}" x2="${p+110+t*(W-p*2-110)}" y1="42" y2="${H-45}" stroke="#dfe7e2"/><text x="${p+110+t*(W-p*2-110)}" y="${H-25}" text-anchor="middle" font-size="11" fill="#66736d">${fmt(max*t,0)}</text>`).join('')}<text x="24" y="28" fill="#006241" font-size="16" font-weight="900">${title}</text>${top.map((x,i)=>{const bw=x.value/max*(W-p*2-110); return `<text x="${p+100}" y="${y(i)+16}" text-anchor="end" font-size="12" fill="#243b33">${esc(x.name).slice(0,24)}</text><rect x="${p+110}" y="${y(i)}" width="${Math.max(3,bw)}" height="22" rx="6" fill="${i%2?'#00a862':'#006241'}"/><text x="${p+118+bw}" y="${y(i)+16}" font-size="12" fill="#003c2f" font-weight="900">${fmt(x.value,1)}</text>`}).join('')}<text x="${W/2}" y="${H-5}" text-anchor="middle" font-size="12" fill="#66736d">Valor</text></svg>`}
function heatmap(rows,type){const entries=entryList(rows,type); const names=entryGroup(rows,type).slice(0,10).map(x=>x.name); const weeks=[...new Set(rows.map(r=>r[C.semana]))].sort((a,b)=>a-b); const map={}; let max=1; entries.forEach(e=>{if(!names.includes(e.name))return; const k=e.name+'|'+e.row[C.semana]; map[k]=(map[k]||0)+e.value; max=Math.max(max,map[k]);}); return `<div class="heat"><div class="heat-row head" style="--cols:${weeks.length}"><b>Concepto</b>${weeks.map(w=>`<b>${w}</b>`).join('')}</div>${names.map(n=>`<div class="heat-row" style="--cols:${weeks.length}"><span>${n}</span>${weeks.map(w=>{const v=map[n+'|'+w]||0; const a=v/max; const cls=a>.66?'hot':a>.33?'mid':'low'; return `<i class="heat-cell ${cls}" title="${n} · Sem ${w}: ${fmt(v,1)}">${v?fmt(v,0):''}</i>`}).join('')}</div>`).join('')}</div>`}
function treemap(rows,type){const items=entryGroup(rows,type).slice(0,12); const total=items.reduce((a,b)=>a+b.value,0)||1; return `<div class="tree">${items.map((x,i)=>`<div class="tile t${i%4}" style="flex-basis:${Math.max(18,x.value/total*100)}%"><b>${x.name}</b><span>${fmt(x.value,1)}</span><small>${pct(x.pct,1)}</small></div>`).join('')}</div>`}
function trendControls(){const opts=['IPLH','TPLH','Ratio','Exactitud_Kronos','NC_Pct','Horas_Planificadas','Items_ADT']; return `<div class="chips">${opts.map(k=>`<button class="chip ${state.trendMetric===k?'on':''}" data-trend="${k}">${metricLabel(k)}</button>`).join('')}</div>`}
function renderInicio(){const {current,prev,all}=currentAndPrev(); const sc=score(current); const cov=avg(current,'Plantilla_Ideal')?avg(current,'Plantilla_Real')/avg(current,'Plantilla_Ideal'):0; return `<div class="hero"><div class="score ${sc.cls}"><small>WFM SCORE</small><strong>${sc.total}</strong><b>${sc.status}</b><div class="scorebar"><i style="width:${sc.total}%"></i></div><div class="score-cols"><div><h4>Fortalezas</h4>${sc.fortalezas.map(x=>`<p>✓ ${x[0]}</p>`).join('')}</div><div><h4>Oportunidades</h4>${sc.oportunidades.map(x=>`<p>⚠ ${x[0]}</p>`).join('')}</div></div></div><div class="kpi-grid">${kpi('IPLH',avg(current,'IPLH'),'IPLH',avg(prev,'IPLH'))}${kpi('TPLH',avg(current,'TPLH'),'TPLH',avg(prev,'TPLH'))}${kpi('Ratio',avg(current,'Ratio'),'Ratio',avg(prev,'Ratio'))}${kpi('% NC',avg(current,'NC_Pct'),'NC_Pct',avg(prev,'NC_Pct'))}${kpi('Horas planificadas',avg(current,'Horas_Planificadas'),'Horas_Planificadas',avg(prev,'Horas_Planificadas'))}${kpi('Exactitud Kronos',avg(current,'Exactitud_Kronos'),'Exactitud_Kronos',avg(prev,'Exactitud_Kronos'))}${kpi('Items / ADT',avg(current,'Items_ADT'),'Items_ADT',avg(prev,'Items_ADT'))}<div class="kpi ${statusBy('Plantilla_Cobertura',cov)[1]}"><div class="kpi-top"><span>Plantilla</span><b>${statusBy('Plantilla_Cobertura',cov)[0]}</b></div><div class="kpi-num">${pct(cov,1)}</div><div class="kpi-note">Ideal ${fmt(avg(current,'Plantilla_Ideal'),0)} · Real ${fmt(avg(current,'Plantilla_Real'),0)}</div></div></div></div><div class="grid two"><div class="card"><h3>¿Qué debo revisar hoy?</h3>${alerts(current,prev).map(alertBox).join('')}<small>Máximo 4 alertas priorizadas por impacto: NC, Código Pago, Items, Forecast y Plantilla.</small></div><div class="card"><div class="card-head"><h3>Tendencia principal</h3>${trendControls()}</div>${lineChart(all,state.trendMetric)}</div></div><div class="grid three"><div class="card"><h3>Top tiendas por IPLH</h3>${barChart(groupBy(current,'tienda','IPLH'), 'IPLH por tienda',5)}</div><div class="card"><h3>Productividad por DM</h3>${barChart(groupBy(current,'dm','IPLH'), 'IPLH promedio por DM',5)}</div><div class="card"><h3>Exactitud Kronos</h3>${lineChart(all,'Exactitud_Kronos')}<p class="note">Rango objetivo: <b>95% a 105%</b>. Dato actual: <b>${pct(avg(current,'Exactitud_Kronos'),1)}</b></p></div></div>`}
function renderIndicadores(){const {current,prev,all}=currentAndPrev(); const metrics=['IPLH','TPLH','Ratio','NC_Pct','Horas_Planificadas','Exactitud_Kronos','Items_ADT','Ordenes_Reales']; const rows=metrics.map(k=>{const now=avg(current,k), old=avg(prev,k), d=delta(now,old), st=statusBy(k,now); return {name:metricLabel(k),value:k==='NC_Pct'||k==='Exactitud_Kronos'?pct(now,1):fmt(now,k==='Ordenes_Reales'?0:1),prev:k==='NC_Pct'||k==='Exactitud_Kronos'?pct(old,1):fmt(old,k==='Ordenes_Reales'?0:1),delta:d,cls:st[1],state:st[0]}}); return `<div class="card"><h3>Indicadores principales</h3>${genericTable(rows,'Indicador')}</div><div class="card"><div class="card-head"><h3>Tendencia configurable</h3>${trendControls()}</div>${lineChart(all,state.trendMetric)}</div>`}
function genericTable(items,label){return `<table class="smart"><thead><tr><th>${label}</th><th>Valor</th><th>Semana ant.</th><th>Variación</th><th>Semáforo</th><th>Estado</th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.value}</td><td>${x.prev}</td><td class="${x.delta>=0?'goodtxt':'badtxt'}">${x.delta>=0?'+':''}${fmt(x.delta,1)}%</td><td><span class="dot ${x.cls}"></span></td><td><span class="pill ${x.cls}">${x.state}</span></td></tr>`).join('')}</tbody></table>`}
function renderPago(){const {current,prev,all}=currentAndPrev(); const items=smartRows(current,prev,'pago'); return `<div class="grid two"><div class="card"><h3>Código Pago Intelligence</h3>${smartTable(items,'Código')}</div><div class="card"><h3>Pareto Código Pago</h3>${barChart(items,'Pareto administrativo',10)}</div></div><div class="grid two"><div class="card"><h3>Heatmap por semana</h3>${heatmap(all,'pago')}</div><div class="card"><h3>Treemap opcional</h3>${treemap(current,'pago')}</div></div>`}
function renderNC(){const {current,prev,all}=currentAndPrev(); const items=smartRows(current,prev,'nc'); return `<div class="grid two"><div class="card"><h3>NC Intelligence</h3>${smartTable(items,'NC')}</div><div class="card"><h3>Pareto NC</h3>${barChart(items,'Pareto incidencias',10)}</div></div><div class="card"><h3>Heatmap NC por semana</h3>${heatmap(all,'nc')}</div>`}
function renderPlantilla(){const {current,prev}=currentAndPrev(); const o={}; current.forEach(r=>{(o[dim(r,'tienda')]??=[]).push(r)}); const op={}; prev.forEach(r=>{(op[dim(r,'tienda')]??=[]).push(r)}); const data=Object.entries(o).map(([name,rs])=>{const ideal=avg(rs,'Plantilla_Ideal'), real=avg(rs,'Plantilla_Real'), cov=ideal?real/ideal:0; const pc=op[name]?avg(op[name],'Plantilla_Ideal')?avg(op[name],'Plantilla_Real')/avg(op[name],'Plantilla_Ideal'):0:0; const st=statusBy('Plantilla_Cobertura',cov); return {name,value:real,pct:cov,previous:pc*100,delta:(cov-pc)*100,cls:st[1],state:st[0],ideal,real,diff:real-ideal};}).sort((a,b)=>a.pct-b.pct); return `<div class="grid two"><div class="card"><h3>Plantilla</h3><table class="smart"><thead><tr><th>Tienda</th><th>Ideal</th><th>Real</th><th>Dif.</th><th>Cobertura</th><th>Estado</th></tr></thead><tbody>${data.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${fmt(x.ideal,0)}</td><td>${fmt(x.real,0)}</td><td class="${x.diff>=0?'goodtxt':'badtxt'}">${x.diff>=0?'+':''}${fmt(x.diff,1)}</td><td>${pct(x.pct,1)}</td><td><span class="pill ${x.cls}">${x.state}</span></td></tr>`).join('')}</tbody></table></div><div class="card"><h3>Cobertura por tienda</h3>${barChart(data.map(x=>({name:x.name,value:x.pct*100})), 'Cobertura %',8)}</div></div>`}
function renderItems(){const {current,prev,all}=currentAndPrev(); const o={}; current.forEach(r=>{(o[dim(r,'tienda')]??=[]).push(r)}); const op={}; prev.forEach(r=>{(op[dim(r,'tienda')]??=[]).push(r)}); const data=Object.entries(o).map(([name,rs])=>{const real=avg(rs,'Items_Reales'), kronos=avg(rs,'Items_Kronos'), ajuste=avg(rs,'Items_Ajuste_SM'), adt=avg(rs,'Items_ADT'), old=op[name]?avg(op[name],'Items_Reales'):0, dev=kronos?((real-kronos)/kronos)*100:0; const cls=Math.abs(dev)>8?'bad':Math.abs(dev)>4?'warn':'good'; return {name,real,kronos,ajuste,adt,dev,previous:old,delta:delta(real,old),cls,state:(cls==='good'?'Excelente':cls==='warn'?'Atención':'Riesgo')};}).sort((a,b)=>Math.abs(b.dev)-Math.abs(a.dev)); return `<div class="grid two"><div class="card"><h3>Items Intelligence</h3><table class="smart"><thead><tr><th>Tienda</th><th>Ajuste SM</th><th>Kronos</th><th>Real</th><th>Items/ADT</th><th>Desv.</th><th>Estado</th></tr></thead><tbody>${data.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${fmt(x.ajuste,0)}</td><td>${fmt(x.kronos,0)}</td><td>${fmt(x.real,0)}</td><td>${fmt(x.adt,2)}</td><td class="${x.dev>=0?'goodtxt':'badtxt'}">${x.dev>=0?'+':''}${fmt(x.dev,1)}%</td><td><span class="pill ${x.cls}">${x.state}</span></td></tr>`).join('')}</tbody></table></div><div class="card"><h3>Desviación Real vs Kronos</h3>${barChart(data.map(x=>({name:x.name,value:Math.abs(x.dev)})), 'Desviación absoluta %',8)}</div></div><div class="card"><h3>Tendencia Items Reales</h3>${lineChart(all,'Items_Reales')}</div>`}
function renderTendencias(){const all=filtered(false); return `<div class="card"><div class="card-head"><h3>Tendencia configurable</h3>${trendControls()}</div>${lineChart(all,state.trendMetric)}<p class="note">Los ejes muestran semana y valor real. Usa los filtros para aislar Región, DM, Tienda, Mes y Semanas.</p></div>`}
function renderReportes(){const {current,prev}=currentAndPrev(); const sc=score(current); return `<div class="report"><div class="cover"><img src="assets/logo.png"><h1>WFM Intelligence</h1><h2>Reporte Ejecutivo</h2><p>Score ${sc.total} · ${sc.status}</p></div>${renderInicio()}<div class="card"><h3>Auditoría de modelo</h3><p>Esta versión usa únicamente columnas con instrucción. Las columnas sin instrucción fueron omitidas del modelo operativo.</p><p>Registros: <b>${int(M.meta.rows)}</b> · Faltantes de instrucción: <b>${M.meta.missing.length}</b></p></div></div>`}
function renderConfig(){return `<div class="card"><h3>Configuración</h3><p><b>Modelo limpio:</b> solo columnas con instrucción.</p><p><b>Actualización mensual:</b> reemplazar <code>data/base.xlsx</code> y ejecutar <code>scripts/refresh_data.py</code> para regenerar <code>data/model.json</code>.</p><p><b>Menú v1.0:</b> Inicio, Indicadores, Código Pago, NC, Plantilla, Items, Tendencias, Reportes y Configuración.</p></div><div class="card"><h3>Columnas usadas</h3><p>${M.metrics.map(metricLabel).join(' · ')}</p><p>Código Pago: ${M.paymentTypes.join(' · ')}</p><p>NC: ${M.ncTypes.join(' · ')}</p></div>`}
function render(){renderNav(); renderFilters(); M.rows.forEach((r,i)=>r._i=i); const view={inicio:renderInicio,indicadores:renderIndicadores,pago:renderPago,nc:renderNC,plantilla:renderPlantilla,items:renderItems,tendencias:renderTendencias,reportes:renderReportes,config:renderConfig}[state.page]; const rs=filtered(); $('#pageTitle').textContent=PAGES.find(p=>p[0]===state.page)[1].replace(/^\S+ /,''); $('#pageSub').textContent=`${int(rs.length)} registros filtrados · modelo limpio v1.0`; $('#view').innerHTML=rs.length?view():'<div class="card"><h3>Sin datos</h3><p>Ajusta los filtros.</p></div>'; document.querySelectorAll('[data-trend]').forEach(b=>b.onclick=()=>{state.trendMetric=b.dataset.trend; render();}); }
async function init(){M=await fetch('data/model.json').then(r=>r.json()); $('#loader').classList.add('hidden'); render(); if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');}
$('#resetBtn').onclick=()=>{state={...state,region:'',dm:'',tienda:'',mes:'',weeks:[],trendMetric:'IPLH'}; render();};
$('#menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
$('#pdfBtn').onclick=()=>window.print();
init();
