const $=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:1}),money=n=>'$'+Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:0});
const PAGES=[['executive','🏠 Executive'],['productividad','📈 Productividad'],['plantilla','👥 Plantilla'],['horas','🕒 Horas'],['pago','💳 Código Pago'],['nc','⚠ NC'],['items','📦 Items'],['tendencias','📊 Tendencias'],['forecast','🎯 Forecast'],['mapa','📍 Mapa'],['reportes','📄 Reportes']];
const COL={region:0,dm:1,tienda:2,cc:3,mes:4,mesNum:5,semana:6,formato:7,categoria:8,lat:9,lng:10};let M,metrics={},state={page:'executive',region:'',dm:'',tienda:'',mes:'',semana:'',formato:'',categoria:''};
function metricIndex(k){return 11+M.k.indexOf(k)}function val(r,k){return +r[metricIndex(k)]||0}function dim(r,k){return M.d[k][r[COL[k]]]||''}
function avg(rows,k){let a=rows.map(r=>val(r,k)).filter(v=>Number.isFinite(v));return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}function sum(rows,k){return rows.reduce((t,r)=>t+val(r,k),0)}
function filtered(){return M.r.filter(r=>(!state.region||dim(r,'region')===state.region)&&(!state.dm||dim(r,'dm')===state.dm)&&(!state.tienda||dim(r,'tienda')===state.tienda)&&(!state.mes||dim(r,'mes')===state.mes)&&(!state.semana||String(r[COL.semana])===String(state.semana))&&(!state.formato||dim(r,'formato')===state.formato)&&(!state.categoria||dim(r,'categoria')===state.categoria))}
function relatedOptions(key){const rows=M.r.filter(r=>(key==='region'||!state.region||dim(r,'region')===state.region)&&(key==='dm'||!state.dm||dim(r,'dm')===state.dm)&&(key==='tienda'||!state.tienda||dim(r,'tienda')===state.tienda)&&(key==='mes'||!state.mes||dim(r,'mes')===state.mes));let vals=[...new Set(rows.map(r=>key==='semana'?r[COL.semana]:dim(r,key)).filter(Boolean))];return vals.sort((a,b)=>key==='semana'?a-b:String(a).localeCompare(String(b),'es'))}
function renderFilters(){const cfg=[['region','Región'],['dm','DM'],['tienda','Tienda'],['mes','Mes'],['semana','Semana'],['formato','Formato'],['categoria','Categoría']];$('#filters').innerHTML=cfg.map(([k,l])=>`<div class="field"><label>${l}</label><select data-filter="${k}"><option value="">Todos</option>${relatedOptions(k).map(v=>`<option ${String(state[k])===String(v)?'selected':''}>${v}</option>`).join('')}</select></div>`).join('');document.querySelectorAll('[data-filter]').forEach(el=>el.onchange=e=>{state[e.target.dataset.filter]=e.target.value;if(['region','dm','tienda','mes'].includes(e.target.dataset.filter)){if(e.target.dataset.filter==='region'){state.dm='';state.tienda=''} if(e.target.dataset.filter==='dm')state.tienda=''}render()})}
function nav(){document.querySelector('#nav').innerHTML=PAGES.map(p=>`<button class="navbtn ${state.page===p[0]?'active':''}" data-page="${p[0]}">${p[1]}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;document.querySelector('.sidebar').classList.remove('open');render()})}
function kpi(title,value,delta,kind=''){let c=delta>0?'up':delta<0?'down':'warn';return `<div class="card"><div class="kpi-title"><span>${title}</span><span class="badge ${kind==='bad'?'bad':''}">${kind||'LIVE'}</span></div><div class="kpi-value">${value}</div><div class="delta ${c}">${delta>0?'↑':delta<0?'↓':'•'} ${Math.abs(delta).toFixed(1)}% vs semana previa</div></div>`}
function prevDelta(rows,k){let weeks=[...new Set(rows.map(r=>r[COL.semana]))].sort((a,b)=>a-b);if(weeks.length<2)return 0;let a=avg(rows.filter(r=>r[COL.semana]===weeks.at(-1)),k),b=avg(rows.filter(r=>r[COL.semana]===weeks.at(-2)),k);return b?((a-b)/Math.abs(b))*100:0}
function group(rows,by,k,fn='avg'){let o={};rows.forEach(r=>{let key=by==='semana'?r[COL.semana]:dim(r,by);(o[key]??=[]).push(r)});return Object.entries(o).map(([name,rs])=>({name,value:fn==='sum'?sum(rs,k):avg(rs,k),rows:rs})).sort((a,b)=>b.value-a.value)}
function lineChart(rows,keys){let weeks=[...new Set(rows.map(r=>r[COL.semana]))].sort((a,b)=>a-b),series=keys.map(k=>weeks.map(w=>avg(rows.filter(r=>r[COL.semana]===w),k)));let all=series.flat(),min=Math.min(...all),max=Math.max(...all),w=760,h=280,p=36;let sx=i=>p+i*(w-2*p)/Math.max(weeks.length-1,1),sy=v=>h-p-((v-min)/(max-min||1))*(h-2*p);return `<svg viewBox="0 0 ${w} ${h}" class="chart"><rect width="100%" height="100%" rx="18" fill="#fffaf0"/>${[0,1,2,3].map(i=>`<line x1="${p}" x2="${w-p}" y1="${p+i*(h-2*p)/3}" y2="${p+i*(h-2*p)/3}" stroke="#dfe7e2"/>`).join('')}${series.map((s,si)=>`<path d="${s.map((v,i)=>(i?'L':'M')+sx(i)+' '+sy(v)).join(' ')}" fill="none" stroke="${si?'#00a862':'#006241'}" stroke-width="4" stroke-linecap="round"/>${s.map((v,i)=>`<circle cx="${sx(i)}" cy="${sy(v)}" r="4" fill="${si?'#00a862':'#006241'}"/>`).join('')}`).join('')}${weeks.map((wk,i)=>`<text x="${sx(i)}" y="${h-10}" font-size="12" text-anchor="middle" fill="#66736d">${wk}</text>`).join('')}<text x="18" y="22" font-size="12" fill="#006241" font-weight="900">${keys.join(' · ')}</text></svg>`}
function bars(items,max=10){let top=items.slice(0,max),m=Math.max(...top.map(x=>x.value),1);return top.map(x=>`<div class="barrow"><div><b>${x.name}</b><div class="bar"><span style="width:${Math.max(3,x.value/m*100)}%"></span></div></div><b>${fmt(x.value)}</b></div>`).join('')}
function table(items,cols=['name','value']){return `<table class="table"><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${items.map(x=>`<tr>${cols.map(c=>`<td>${c==='value'?fmt(x[c]):x[c]}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function normGroup(rows,type){let indices=new Set(rows.map(r=>r._i));let arr=(type==='pago'?M.p:M.nc),types=(type==='pago'?M.pt:M.nt),o={};arr.forEach(a=>{if(indices.has(a[0]))o[types[a[1]]]=(o[types[a[1]]]||0)+a[2]});return Object.entries(o).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
function heat(rows,type){let weeks=[...new Set(rows.map(r=>r[COL.semana]))].sort((a,b)=>a-b).slice(-8),types=normGroup(rows,type).slice(0,8).map(x=>x.name),arr=type==='pago'?M.p:M.nc,typelist=type==='pago'?M.pt:M.nt,idxByRecord=new Map(rows.map(r=>[M.r.indexOf(r),r]));let vals=[],max=1;types.forEach(t=>weeks.forEach(w=>{let s=0;arr.forEach(a=>{let r=idxByRecord.get(a[0]);if(r&&typelist[a[1]]===t&&r[COL.semana]===w)s+=a[2]});vals.push(s);max=Math.max(max,s)}));let n=0;return `<div class="heat" style="--cols:${weeks.length}"><div class="heat-row"><b>Tipo / Semana</b>${weeks.map(w=>`<b>${w}</b>`).join('')}</div>${types.map(t=>`<div class="heat-row"><span>${t}</span>${weeks.map(w=>{let v=vals[n++];return `<div class="heat-cell" style="--a:${.08+.75*v/max}">${v?fmt(v):''}</div>`}).join('')}</div>`).join('')}</div>`}
function insights(rows){let pay=normGroup(rows,'pago')[0]||{}, nc=normGroup(rows,'nc')[0]||{}, dm=group(rows,'dm','IPLH')[0]||{}, stores=group(rows,'tienda','Items_Reales').map(x=>{let kr=avg(x.rows,'Items_Kronos_Proy'),re=avg(x.rows,'Items_Reales');return {name:x.name,value:kr?((re-kr)/kr)*100:0}}).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value))[0]||{};return [`El mayor uso administrativo está en <b>${pay.name||'sin dato'}</b> con ${fmt(pay.value||0)} horas.`,`El NC que más impacta es <b>${nc.name||'sin dato'}</b> con ${fmt(nc.value||0)} horas.`,`El mejor DM por IPLH es <b>${dm.name||'sin dato'}</b> con ${fmt(dm.value||0)}.`,`La mayor desviación Items Real vs Kronos está en <b>${stores.name||'sin dato'}</b>: ${fmt(stores.value||0)}%.`].map(t=>`<div class="insight"><span class="badge">Insight</span><div>${t}</div></div>`).join('')}
function executive(rows){return `<div class="page"><div class="grid kpis">${kpi('IPLH',fmt(avg(rows,'IPLH')),prevDelta(rows,'IPLH'))}${kpi('TPLH',fmt(avg(rows,'TPLH')),prevDelta(rows,'TPLH'))}${kpi('Ratio',fmt(avg(rows,'Ratio')),prevDelta(rows,'Ratio'))}${kpi('Exactitud Kronos',fmt(avg(rows,'Exactitud_Kronos'))+'%',prevDelta(rows,'Exactitud_Kronos'))}${kpi('Plantilla',fmt(avg(rows,'Emp_Reales'))+' / '+fmt(avg(rows,'Emp_Autorizados')),prevDelta(rows,'Emp_Reales'))}${kpi('% NC',fmt(avg(rows,'NC'))+'%',prevDelta(rows,'NC'),avg(rows,'NC')>10?'bad':'')}${kpi('Items Reales',fmt(avg(rows,'Items_Reales')),prevDelta(rows,'Items_Reales'))}${kpi('Horas Plan',fmt(avg(rows,'Horas_Planificadas')),prevDelta(rows,'Horas_Planificadas'))}</div><div class="section-title"><div><h3>Tendencia ejecutiva</h3><p>IPLH y TPLH por semana</p></div></div><div class="grid two"><div class="card">${lineChart(rows,['IPLH','TPLH'])}</div><div class="card"><h3>Decisiones sugeridas</h3>${insights(rows)}</div></div></div>`}
function productividad(rows){let top=group(rows,'tienda','IPLH').slice(0,10),bottom=group(rows,'tienda','IPLH').sort((a,b)=>a.value-b.value).slice(0,10);return `<div class="page grid two"><div class="card"><h3>Top tiendas por IPLH</h3>${bars(top)}</div><div class="card"><h3>Mayor oportunidad por IPLH</h3>${bars(bottom)}</div><div class="card"><h3>Productividad por DM</h3>${table(group(rows,'dm','IPLH').slice(0,12))}</div><div class="card"><h3>Tendencia Productividad</h3>${lineChart(rows,['IPLH','TPLH'])}</div></div>`}
function plantilla(rows){let deficit=group(rows,'tienda','Emp_Reales').map(x=>({name:x.name,value:avg(x.rows,'Emp_Reales')-avg(x.rows,'Emp_Autorizados')})).sort((a,b)=>a.value-b.value);return `<div class="page"><div class="grid kpis">${kpi('Plantilla ideal',fmt(avg(rows,'Emp_Autorizados')),0)}${kpi('Plantilla real',fmt(avg(rows,'Emp_Reales')),prevDelta(rows,'Emp_Reales'))}${kpi('Déficit promedio',fmt(avg(rows,'Emp_Reales')-avg(rows,'Emp_Autorizados')),0,'')}${kpi('Capacidad instalada',fmt(avg(rows,'Capacidad_Instalada'))+'%',prevDelta(rows,'Capacidad_Instalada'))}</div><div class="grid two"><div class="card"><h3>Tiendas con déficit</h3>${table(deficit.slice(0,15))}</div><div class="card"><h3>Tendencia plantilla</h3>${lineChart(rows,['Emp_Reales','Emp_Autorizados'])}</div></div></div>`}
function horas(rows){return `<div class="page grid two"><div class="card"><h3>Forecast vs Plan vs Kronos</h3>${lineChart(rows,['Horas_Fcst','Horas_Planificadas','Horas_Kronos'])}</div><div class="card"><h3>Horas planificadas por DM</h3>${bars(group(rows,'dm','Horas_Planificadas','sum'),12)}</div><div class="card"><h3>Venta perdida</h3>${bars(group(rows,'tienda','Venta_Perdida','sum'),10)}</div><div class="card"><h3>Gasto adicional</h3>${bars(group(rows,'tienda','Gasto_adicional','sum'),10)}</div></div>`}
function pago(rows){let g=normGroup(rows,'pago');return `<div class="page grid two"><div class="card"><h3>Pareto Código de Pago</h3>${bars(g,15)}</div><div class="card"><h3>Heatmap semanas</h3>${heat(rows,'pago')}</div><div class="card"><h3>Ranking Código Pago</h3>${table(g.slice(0,20))}</div><div class="card"><h3>Insight</h3>${insights(rows)}</div></div>`}
function nc(rows){let g=normGroup(rows,'nc');return `<div class="page grid two"><div class="card"><h3>Pareto NC</h3>${bars(g,15)}</div><div class="card"><h3>Heatmap NC</h3>${heat(rows,'nc')}</div><div class="card"><h3>Ranking NC</h3>${table(g.slice(0,20))}</div><div class="card"><h3>Tendencia % NC</h3>${lineChart(rows,['NC'])}</div></div>`}
function items(rows){let data=group(rows,'tienda','Items_Reales').map(x=>{let a=avg(x.rows,'Items_Gerente_Aj'),k=avg(x.rows,'Items_Kronos_Proy'),r=avg(x.rows,'Items_Reales');return {name:x.name,Ajuste:a,Kronos:k,Real:r,Desv:k?((r-k)/k)*100:0}}).sort((a,b)=>Math.abs(b.Desv)-Math.abs(a.Desv)).slice(0,15);return `<div class="page"><div class="grid kpis">${kpi('Items Ajuste SM',fmt(avg(rows,'Items_Gerente_Aj')),prevDelta(rows,'Items_Gerente_Aj'))}${kpi('Items Kronos',fmt(avg(rows,'Items_Kronos_Proy')),prevDelta(rows,'Items_Kronos_Proy'))}${kpi('Items Reales',fmt(avg(rows,'Items_Reales')),prevDelta(rows,'Items_Reales'))}${kpi('Desviación Real vs Kronos',fmt(((avg(rows,'Items_Reales')-avg(rows,'Items_Kronos_Proy'))/(avg(rows,'Items_Kronos_Proy')||1))*100)+'%',0)}</div><div class="grid two"><div class="card"><h3>Tendencia Items</h3>${lineChart(rows,['Items_Gerente_Aj','Items_Kronos_Proy','Items_Reales'])}</div><div class="card"><h3>Mayor desviación por tienda</h3>${table(data,['name','Ajuste','Kronos','Real','Desv'])}</div></div></div>`}
function tendencias(rows){return `<div class="page grid"><div class="card"><h3>Indicadores principales</h3>${lineChart(rows,['IPLH','TPLH','Ratio','Exactitud_Kronos'])}</div><div class="grid three"><div class="card"><h3>Top DM IPLH</h3>${bars(group(rows,'dm','IPLH'),8)}</div><div class="card"><h3>Top Código Pago</h3>${bars(normGroup(rows,'pago'),8)}</div><div class="card"><h3>Top NC</h3>${bars(normGroup(rows,'nc'),8)}</div></div></div>`}
function forecast(rows){return `<div class="page grid two"><div class="card"><h3>Forecast Intelligence</h3>${lineChart(rows,['Horas_Fcst','Horas_Planificadas','Horas_Kronos'])}</div><div class="card"><h3>Brecha Forecast vs Plan</h3>${bars(group(rows,'tienda','Horas_Planificadas').map(x=>({name:x.name,value:avg(x.rows,'Horas_Planificadas')-avg(x.rows,'Horas_Fcst')})).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)),12)}</div></div>`}
function mapa(rows){let pts=group(rows,'tienda','IPLH').map(x=>({name:x.name,value:x.value,lat:x.rows[0][COL.lat],lng:x.rows[0][COL.lng]})).filter(x=>x.lat&&x.lng);return `<div class="page card"><h3>Mapa operativo</h3><p>Representación ejecutiva por coordenadas. Verde = mejor IPLH, rojo = oportunidad.</p><svg viewBox="0 0 900 480" class="chart"><rect width="900" height="480" rx="24" fill="#fffaf0"/>${pts.map(p=>{let x=(p.lng+102.5)*170,y=(22-p.lat)*120,c=p.value>16?'#008248':p.value>12?'#b7791f':'#b42318';return `<circle cx="${x}" cy="${y}" r="7" fill="${c}"><title>${p.name} · IPLH ${fmt(p.value)}</title></circle>`}).join('')}<text x="24" y="36" fill="#006241" font-weight="900">Tiendas geolocalizadas: ${pts.length}</text></svg></div>`}
function reportes(rows){return `<div class="page"><div class="print-only"><h1>WFM Intelligence · Planning is Key</h1><p>Filtros: Región ${state.region||'Todas'} · DM ${state.dm||'Todos'} · Tienda ${state.tienda||'Todas'} · Mes ${state.mes||'Todos'} · Semana ${state.semana||'Todas'}</p></div>${executive(rows)}<div class="card"><h3>Resumen para seguimiento</h3>${table([{name:'Filas analizadas',value:rows.length},{name:'Código Pago total',value:normGroup(rows,'pago').reduce((a,b)=>a+b.value,0)},{name:'NC total',value:normGroup(rows,'nc').reduce((a,b)=>a+b.value,0)},{name:'Venta perdida',value:sum(rows,'Venta_Perdida')}])}</div></div>`}
function render(){nav();renderFilters();let rows=filtered();$('#pageTitle').textContent=PAGES.find(p=>p[0]===state.page)[1].replace(/^[^ ]+ /,'');$('#pageSub').textContent=`${rows.length.toLocaleString('es-MX')} registros filtrados · ${M.m.rows.toLocaleString('es-MX')} base total`;let map={executive,productividad,plantilla,horas,pago,nc,items,tendencias,forecast,mapa,reportes};$('#view').innerHTML=rows.length?map[state.page](rows):'<div class="card"><h3>Sin datos</h3><p>Ajusta los filtros.</p></div>'}
async function init(){M=await fetch('data/model.json').then(r=>r.json());M.r.forEach((r,i)=>r._i=i);M.k.forEach((k,i)=>metrics[k]=11+i);$('#loader').classList.add('hidden');render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');}
$('#resetBtn').onclick=()=>{state={...state,region:'',dm:'',tienda:'',mes:'',semana:'',formato:'',categoria:''};render()};$('#pdfBtn').onclick=()=>window.print();$('#menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');init();
